#!/bin/bash

ROOT="`dirname \"$0\"`" # Relative
export ROOT="`( cd \"$ROOT\" && pwd )`" # Absolutized and normalized
[[ -f ./scripts/tools ]] && source ./scripts/tools

function usage () {
	echo '
  viewerAPI command [arg]

    auth           - get an access token (no argument)
    buckets [[-s] [limit] [index]]
                   - list local buckets
                     -s / --server : list buckets on the server
                       limit: <optional=10> how many to return
                       index: <optional=0> where to start in the list
                       ex: -s 10 30 -> will return the 30th to the 39th items
    bucket [<Name>]
                   - set or get the current bucket
    bucketCreate <Name> [<Type>]
                   - create a new bucket,
                     default Type is transient, values can be
                     transient/temporary/permanent
    bucketCheck [<Name>]
                   - check bucket validity, outputs the expiration
                     date/time for this bucket
                     if no parameter use the current bucket
    bucketItems [<Name>]
                   - list items in a given bucket
                     required to be in the API white list to use this API
                     if no parameter use the current bucket
	bucketDelete [<Name>]
                   - delete a given bucket
                     if no parameter delete the current bucket
    upload [-h] <File>
                   - upload a file in the current bucket
                     -h for list of supported format
	download <FileKey> <OutputFile>
                   - download the file from OSS
    objectDetails <FileKey>
                   - file information
    register <FileKey>
                   - translate the file for viewing
    registerProgress <FileKey>
                   - file translation progress
    viewable <FileKey> [<subCommand>]
                   - get viewable information
                     subcommand: nothing - all - all?guid= - status - status?guid=
    thumbnail <FileKey>
                   - get thumbnail
    html <FileKey>
                   - generate default html page and view in browser
    setReferences <FileKeyMaster> <FileIdChild> [<FileIdChild>...]
                   - set file references
    setReferencesUsingBuckets <FileKeyMaster>
                   - set file references
    deleteViewables <FileKey>
                   - delete viewable/bubbles from server (after translation)
    deleteFile <FileKey>
                   - delete the source file from the bucket
'
}

case "$1" in
	"help" | "usage" | "-h" | "")
		usage
		exit
		;;
	"auth")
		source $ROOT/scripts/auth
		;;
	"bucket")
		if [ "$2" == "" ]; then
			echo -n "Current bucket is: "
			cat $ROOT/data/bucket
			exit
		fi
		bucket=$(bucketName $2)
		if [ "$bucket" != "" ]; then
			echo $bucket > $ROOT/data/bucket
		else
			echo "Error: missing bucket name or invalid!"
			exit
		fi
		;;
	"buckets")
		if [ "$2" != "-s" ] && [ "$2" != "--server" ]; then
			regex="(.*)\.bucket\.json"
			ll=$(ls $ROOT/data/*.bucket.json)
			for l in $ll; do
				lb=$(basename $l)
				[[ $lb =~ $regex ]]
				name="${BASH_REMATCH[1]}"
				echo $name
			done
			exit
		fi
		cmd=$1
		shift
		shift # -s / -- server
		$ROOT/scripts/${cmd} "$@"
		;;
	# "bucketCreate") "bucketCheck") "upload") "objectDetails")
	# "register") "registerProgress") "viewable") "thumbnail")
	# "html") "setReferences") "setReferencesUsingBuckets")
	*)
		cmd=$1
		shift
		$ROOT/scripts/${cmd} "$@"
		;;
esac
