#!/bin/bash

# Step 1: Request and install your credentials

[[ -f ./tools ]] && source ./tools
[[ -f ./scripts/tools ]] && source ./scripts/tools
source $ROOT/scripts/credentials

# Step 2: Get your access token

response=$(curl --data "client_id=${ConsumerKey}&client_secret=${ConsumerSecret}&grant_type=client_credentials" ${APIHost}authentication/v1/authenticate --header "Content-Type: application/x-www-form-urlencoded" -k)

#echo $response | python -m json.tool

token_type=$(echo $response | jsonValue token_type 1)
if [ "$token_type" == "" ]; then
	msg=$(echo $response | jsonValue "faultstring" 1)
	echo "Failed to get your token"
	echo "  $msg"
	[[ -f $ROOT/data/access_token ]] && rm $ROOT/data/access_token
	exit
fi
access_token=$(echo $response | jsonValue access_token 1)
expires_in=$(echo $response | jsonValue expires_in 1)
if [ "$OS" == "Windows_NT" ]; then
	dt=$(date -d "+${expires_in} seconds")
else
	dt=$(date -v "+${expires_in}S")
fi

echo "Your new access token is: ${token_type} ${access_token}"
echo "Expires at $dt"

echo "${token_type} ${access_token}" > $ROOT/data/access_token
