#!/bin/bash

[[ -f ./_tools ]] && source ./_tools
[[ -f ./scripts/_tools ]] && source ./scripts/_tools
source $ROOT/scripts/_config

#    bucketDelete [<Name>]
#                   - delete a given bucket
#                     if no parameter delete the current bucket

bucket=$(bucketName $1)
if [[ "$bucket" == "" ]]; then
	echo "Error: missing bucket name or invalid name!"
	exit
fi

echo "Deleting bucket: ${bucket}"
response=$(curl -H "Authorization: ${access_token}" -X DELETE ${APIHost}oss/v2/buckets/${bucket} -k)
echo $response | jq .
