#!/bin/bash

[[ -f ./tools ]] && source ./tools
[[ -f ./scripts/tools ]] && source ./scripts/tools
source $ROOT/scripts/credentials

if [ "$1" != "" ]; then
	bucket=$(bucketName $1)
	if [[ $bucket == "" ]]; then
		echo "Error: missing bucket name or invalid!"
		exit
	fi
fi

response=$(curl -H "Authorization: ${access_token}" -X GET ${APIHost}oss/v1/buckets/${bucket}/details -k)
#echo $response | python -m json.tool

errorCode=$(echo $response | jsonValue errorCode 1)
if [ "$errorCode" != "" ]; then
	developerMessage=$(echo $response | jsonValue developerMessage 1)
	echo "${errorCode} - ${developerMessage}"
	exit
fi

#dtv=$(echo $response | jsonValue createdDate 1)
#dt=$(date -r "$dtv")
#echo "createDate = $dt"
#dt=$(date -r "$dtv" -v +30d)

policyKey=$(echo $response | jsonValue policyKey 1)
if [ "$policyKey" == "transient" ]; then # 24 hours
	echo "bucket content will expire after: 24 hours"
elif [ "$policyKey" == "temporary" ]; then # 30 days
	echo "bucket content will expire after: 30 days"
else # persistent
	echo "bucket content will never expire"
fi
