#!/bin/bash

[[ -f ./_tools ]] && source ./_tools
[[ -f ./scripts/_tools ]] && source ./scripts/_tools
source $ROOT/scripts/_config

#    bucketCheck [<Name>]
#                   - check bucket validity, outputs the expiration
#                     date/time for this bucket
#                     if no parameter use the current bucket

bucket=$(bucketName $1)
if [[ "$bucket" == "" ]]; then
	echo "Error: missing bucket name or invalid name!"
	exit
fi

response=$(curl -H "Authorization: ${access_token}" -X GET ${APIHost}oss/v2/buckets/${bucket}/details -k)
#echo $response | jq .

reason=$(echo $response | jq --raw-output .reason)
if [ "$reason" != "null" ]; then
	echo "${reason}"
	exit
fi

policyKey=$(echo $response | jq --raw-output .policyKey)
if [ "$policyKey" == "transient" ]; then # 24 hours
	echo "bucket content will expire after: 24 hours"
elif [ "$policyKey" == "temporary" ]; then # 30 days
	echo "bucket content will expire after: 30 days"
else # persistent
	echo "bucket content will never expire"
fi
