#!/bin/bash

[[ -f ./_tools ]] && source ./_tools
[[ -f ./scripts/_tools ]] && source ./scripts/_tools
source $ROOT/scripts/_config

#    deleteFile <FileKey>
#          - urn manifest

master=$1
masterUri=`echo "$master" | sed 's/ /+/g'`
masterHdd=`echo "$masterUri" | sed 's/+/ /g'`

response=$(curl -i -H "Authorization: ${access_token}" \
	-X DELETE ${APIHost}oss/v2/buckets/{$bucket}/objects/{$masterUri} -k)
echo $response
