#!/bin/bash

[[ -f ./_tools ]] && source ./_tools
[[ -f ./scripts/_tools ]] && source ./scripts/_tools
source $ROOT/scripts/_config

#    download <FileKey> <OutputFile>
#          - download the file from OSS

master=$1
masterUri=`echo "$master" | sed 's/ /+/g'`
masterHdd=`echo "$masterUri" | sed 's/+/ /g'`

output=$2
temp="$ROOT/temp/${output}.tmp"
headers="$ROOT/temp/${output}.txt"

response=$(curl -i -H "Authorization: ${access_token}" -o ${temp} -D ${headers} \
	-X GET ${APIHost}oss/v2/buckets/${bucket}/objects/${masterUri} -k)
#cat $headers

bytes=`cat ${headers} | grep -i 'Content-Length' | tr -d '\r' | sed 's/Content-Length: \([0-9]*\)/\1/'`
hcount=`wc -c ${headers} | sed 's/[ ]*\([0-9]*\).*/\1/'`
echo "bytes count = ${bytes} - headers = ${hcount}"

rm $headers
#echo "tail -c $bytes $temp > $output"
tail -c $bytes $temp > $output
rm $temp
