#!/bin/bash

[[ -f ./tools ]] && source ./tools
[[ -f ./scripts/tools ]] && source ./scripts/tools
source $ROOT/scripts/credentials

master=$1
masterUri=`echo $master | sed 's/ /+/g'`
masterHdd=`echo $masterUri | sed 's/+/ /g'`

id=$(cat "$ROOT/data/${bucket}.${masterHdd}.json" | jsonValueAtPath '["objects"][0]["id"]')
id64=$(xbase64encode $id)

# Generate local viewer
echo -n '<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<link type="text/css" rel="stylesheet" href="https://developer.api.autodesk.com/viewingservice/v1/viewers/style.css">
<script src="https://developer.api.autodesk.com/viewingservice/v1/viewers/viewer3D.min.js"></script>
</head>
<body onload="initialize()">
  <div id="viewer" style="position:absolute; width:90%; height:90%;"></div>
<script>
function initialize () {
  var options ={ "document" : "urn:' > "$ROOT/temp/${masterUri}.html"
echo -n $id64 >> "$ROOT/temp/${masterUri}.html"
echo '" } ;
  var viewerElement =document.getElementById ("viewer") ;
  //var viewer =new Autodesk.Viewing.Viewer3D (viewerElement, {}) ; / No toolbar
  var viewer =new Autodesk.Viewing.Private.GuiViewer3D (viewerElement, {}) ; // With toolbar
  Autodesk.Viewing.Initializer (options, function () {
   viewer.initialize () ;
   loadDocument (viewer, getURLParameterByName ("accessToken"), options.document) ;
  }) ;
}

function getURLParameterByName (name) {
    name =name.replace (/[\[]/, "\\[").replace (/[\]]/, "\\]") ;
    var regex =new RegExp ("[\\?&]" + name + "=([^&#]*)") ;
    results =regex.exec (location.search) ;
    return (results == null ? "" : decodeURIComponent (results [1].replace (/\+/g, " "))) ;
}

function loadDocument (viewer, auth, documentId) {
    // Find the first 3d geometry and load that.
    Autodesk.Viewing.Document.load (documentId, auth,
	  function (doc) { // onLoadCallback
        var geometryItems =[] ;
        geometryItems =Autodesk.Viewing.Document.getSubItemsWithProperties (doc.getRootItem (), { "type" : "geometry", "role" : "3d" }, true) ;
        if ( geometryItems.length > 0 )
          viewer.load (doc.getViewablePath (geometryItems [0])) ;
      },
	  function (errorMsg) { // onErrorCallback
        alert("Load Error: " + errorMsg) ;
      }) ;
}
</script>
</body>
</html>' >> "$ROOT/temp/${masterUri}.html"

cp -f "$ROOT/temp/${masterUri}.html" $LocalhostFolder

access_token=$(echo $access_token | sed 's/Bearer //')
if [[ "${LocalhostFolder}" =~ "\\~.*" ]] || [[ "${LocalhostFolder}" =~ "/Users/${USER}/Sites" ]]; then
	python -mwebbrowser "http://localhost/~${USER}/${masterUri}.html?accessToken=${access_token}"
else
	python -mwebbrowser "http://localhost/${masterUri}.html?accessToken=${access_token}"
fi
