#!/bin/bash

[[ -f ./tools ]] && source ./tools
[[ -f ./scripts/tools ]] && source ./scripts/tools
source $ROOT/scripts/credentials

# Step 5: Setup References between multiple files
master=$1
id=$(cat $ROOT/data/${bucket}.${master}.json | jsonValueAtPath '["objects"][0]["id"]')
parentPath=$(basename $id)
st="{ \"master\" : \"${id}\", \"dependencies\" : ["

for f in "$@"; do
	if [ "$f" == "${master}" ]; then
		continue
	fi
	id=$(cat $ROOT/data/${bucket}.${f}.json | jsonValueAtPath '["objects"][0]["id"]')
	childPath=$(basename $id)
	st=$st"{ \"file\" : \"${id}\", \"metadata\" : { \"childPath\" : \"${childPath}\", \"parentPath\" : \"$parentPath\" } },"
done
st="${st%?}] }"
#echo $st | python -m json.tool

#echo $st > test.txt
#response=$(curl -H "Content-Type: application/json" -H "Authorization: ${access_token}" -i -d @test.txt ${APIHost}references/v1/setreference -k)
response=$(curl -H "Content-Type: application/json" -H "Authorization: ${access_token}" -i -d "${st}" ${APIHost}references/v1/setreference -k)
#echo $response | tr -d '\015'
if [[ $response == *"HTTP/1.1 200 OK"* ]]; then
	echo "References successfully submitted."
else
	echo "References submission failed!"
	echo $response | tr -d '\015'
fi
