#!/bin/bash

[[ -f ./_tools ]] && source ./_tools
[[ -f ./scripts/_tools ]] && source ./scripts/_tools
source $ROOT/scripts/_config

#    thumbnail <FileKey>
#          - get thumbnail

master=$1
masterUri=`echo "$master" | sed 's/ /+/g'`
masterHdd=`echo "$masterUri" | sed 's/+/ /g'`

id="urn:adsk.objects:os.object:${bucket}/${masterUri}"
id64=$(xbase64safeencode $id)

curl -H "Content-Type: application/json" -H "Authorization: ${access_token}" \
	-X GET ${APIHost}viewingservice/v1/thumbnails/${id64} -k > "$ROOT/temp/${masterHdd}.png"

if [ -f "$ROOT/temp/${masterHdd}.png" ] && [ -s "$ROOT/temp/${masterHdd}.png" ]; then
    test=`file "$ROOT/temp/${masterHdd}.png" | grep "PNG image data"`
    if [ "$test" != "" ]; then
		if [ "$OS" == "Windows_NT" ]; then
			echo "Your preview file is stored in '$ROOT/temp/${masterHdd}.png'"
		else
			echo "Your preview file is stored in '$ROOT/temp/${masterHdd}.png'"
			open "$ROOT/temp/${masterHdd}.png"
		fi
    else
        echo "Error: Not a PNG file or corrupted PNG! Maybe the thumbnail is not yet ready, try again later."
    fi
else
	echo "Error: Thumbnail not generated!"
fi
