#!/bin/bash

if [ "$ROOT" == "" ]; then
	ROOT="`dirname \"$0\"`" # Relative
	export ROOT="`( cd \"$ROOT\" && pwd )`" # Absolutized and normalized
	if [ $(basename $ROOT) == scripts ]; then
		export ROOT=$(dirname $ROOT)
	fi
fi

function jsonValue () {
	local KEY=$1
	local num=$2
	awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'$KEY'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
}

function jsonValueAtPath () {
	local KEY=$1
	cat | python -c "import json,sys;obj=json.load(sys.stdin);print obj${KEY}"
}

function xbase64encode () {
	#id64=$(echo $1 | base64 -) # not correct
	local id=$1
	local id64=$(python -c "import base64,sys;print base64.b64encode(\"${id}\")")
	echo $id64
}

function xbase64decode () {
	local id=$(echo $1 | base64 --decode)
	echo $id
}

function bucketName () {
	local key=$1
	chk=$(echo $key | grep -E "^[-_.a-z0-9]{3,128}$")
	echo $chk
}
