#!/bin/bash

[[ -f ./_tools ]] && source ./_tools
[[ -f ./scripts/_tools ]] && source ./scripts/_tools
source $ROOT/scripts/_config

#    upload <File>
#          - upload a file in the current bucket

if [ ! -f "$1" ]; then
	echo "File not found: $1"
	exit
fi

fullpath=$1
filename=$(basename "$fullpath")
filenameUri=`echo "$filename" | sed 's/ /+/g'`

response=$(curl --header "Authorization: ${access_token}" -H "Content-Type: application/octet-stream" \
	--upload-file "$fullpath" -X PUT "${APIHost}oss/v2/buckets/${bucket}/objects/${filenameUri}" -k)
#echo $response | jq .

reason=$(echo $response | jq --raw-output .reason)
if [ "$reason" != "null" ]; then
	echo "${reason}"
	exit
fi

id=$(echo $response | jq --raw-output .objectId)
echo "ID: $id"
location=$(echo $response | jq --raw-output .location)
echo "Location: $location"

filenameHdd=`echo "$filenameUri" | sed 's/+/ /g'`
echo $response > "$ROOT/data/${bucket}.${filenameHdd}.json"
