#!/bin/bash

[[ -f ./tools ]] && source ./tools
[[ -f ./scripts/tools ]] && source ./scripts/tools
source $ROOT/scripts/credentials

master=$1
masterUri=`echo $master | sed 's/ /+/g'`
masterHdd=`echo $masterUri | sed 's/+/ /g'`

command=$2 # nothing - all - all?guid= - status - status?guid=
id=$(cat "$ROOT/data/${bucket}.${masterHdd}.json" | jsonValueAtPath '["objects"][0]["id"]')
id64=$(xbase64encode $id)

# Get viewables
if [ "$command" == "" ]; then
	response=$(curl -i -H "Content-Type: application/json" -H "Authorization: ${access_token}" -X GET ${APIHost}viewingservice/v1/${id64} -k)
else
	response=$(curl -i -H "Content-Type: application/json" -H "Authorization: ${access_token}" -X GET ${APIHost}viewingservice/v1/${id64}/${command} -k)
fi
if [[ $response == *"HTTP/1.1 200 OK"* ]]; then
	echo $response | tr -d '\015' | sed 's/.*keep-alive//' | python -m json.tool
else
	echo "Request failed!"
	echo $response | tr -d '\015'
fi

#echo $response | tr -d '\015' | sed 's/.*keep-alive//' | python -m json.tool
#echo $response > test.txt
#echo $response | tr -d '\015' | sed 's/.*keep-alive//'
